openapi: 3.1.0
info:
  title: Orchestration Service API
  version: v1
  description: >
    REST API for role-based authorization and access requirements management for biometric security devices.
    Integrates with HikCentral and WSO2 Identity Server for facial recognition and access control.

servers:
  - url: http://localhost:5000
    description: Local development server

tags:
  - name: common
    description: Common endpoints such as health checks.
  - name: requirements
    description: Endpoints for managing and retrieving access requirements and device data.
  - name: authorization
    description: Endpoints for role-based authorization based on biometric processing results.
  - name: event-receive
    description: Endpoints for receiving biometric event data from HikCentral.

paths:
  /health:
    get:
      tags: [common]
      summary: Health check
      description: Returns the health status of the orchestration service.
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  message:
                    type: string
                    example: Service is running


  /api/v1/authorization/authorize-for-door-access:
    post:
      tags: [authorization]
      summary: Authorize user for door access
      description: >
        Receives results of processing biometric data (e.g., facial recognition) from HikCentral, queries WSO2 IDP for user roles,
        and determines if the user is authorized to access a specific door.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmissionForAuthorization'
      responses:
        '200':
          description: Authorization result and user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationResponse'
        '400':
          description: Invalid request body
        '500':
          description: Internal server error

  /api/v1/requirements/reload-requirements-file:
    get:
      tags: [requirements]
      summary: Reload access requirements file
      description: Reloads the access requirements file from disk and updates the in-memory configuration.
      responses:
        '200':
          description: Successfully reloaded access requirements
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Successfully reloaded access requirements
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to reload access requirements file

  /api/v1/requirements/configured-requirements-file-path:
    get:
      tags: [requirements]
      summary: Get configured requirements file path
      description: Returns the file path of the currently configured access requirements file.
      responses:
        '200':
          description: Configured requirements file path
          content:
            application/json:
              schema:
                type: object
                properties:
                  configured_requirements_file_path:
                    type: string
                    example: /path/to/accessRequirementsForDevices.json
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to get configured requirements file path
  /api/v1/event-receive/receive-face-match-event:
    post:
      tags: [event-receive]
      summary: Receive face match event from HikCentral
      description: >
        Endpoint to receive biometric event data (e.g., face match results) from HikCentral.
        This data will be processed to determine user identity and access authorization.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FaceMatchEventNotificationObject'
      responses:
        '200':
          description: Event received and processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Event received and processed successfully
        '400':
          description: Invalid request body
        '500':
          description: Internal server error
  /api/v1/cache-eviction/evict-user-from-cache/{userName}:
    delete:
      tags: [cache-eviction]
      summary: Evict user from cache
      description: Removes the specified user from the Authorizations Cache.
      parameters:
        - name: userName
          in: path
          required: true
          description: Name of the user to evict from cache
          schema:
            type: string
      responses:
        '200':
          description: User cache evicted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User cache evicted successfully
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to evict user from cache
components:
  schemas:
    SubmissionForAuthorization:
      type: object
      properties:
        user_id:
          type: string
          example: skf2425
          description: Unique user identifier from HikCentral
        name:
          type: string
          example: John Doe
          description: Name of the recognized user
        description:
          type: string
          example: Part of the ops department
          description: Description of the biometric event
        device_id:
          type: string
          example: sfhsfig324r
          description: Unique identifier for the device
      required:
        - user_id
        - device_id

    AuthorizationResponse:
      type: object
      properties:
        message:
          type: string
          example: User is authorized to access this device
          description: short message describing whether the user is authorized

    AccessRequirementsObject:
      type: object
      properties:
        deviceId:
          type: string
          example: sfhsfig324r
          description: Unique identifier for the security device
        requiredRole:
          type: string
          example: AccessLevel1
          description: Role required for access
    FaceMatchEventNotificationObject:
      type: object
      properties:
        method:
          type: string
          example: OnEventNotify
        params:
          type: object
          properties:
            sendTime:
              type: string
              format: date-time
              example: 2025-09-15T13:34:12+05:00
            ability:
              type: string
              example: event_face_match
            events:
              type: array
              items:
                type: object
                properties:
                  eventId:
                    type: string
                    example: C219A520D0BD4214AD894EBACA9C32ED
                  srcIndex:
                    type: string
                    example: "2"
                  srcType:
                    type: string
                    example: camera
                  srcName:
                    type: string
                    example: 11th-MainLift
                  eventType:
                    type: integer
                    example: 131659
                  status:
                    type: integer
                    example: 0
                  happenTime:
                    type: string
                    format: date-time
                    example: 2025-09-15T13:34:12+05:30
                  data:
                    type: object
                    properties:
                      dataType:
                        type: string
                        example: faceMatch
                      alarmResult:
                        type: object
                        properties:
                          faces:
                            type: object
                            properties:
                              identify:
                                type: object
                                properties:
                                  candidate:
                                    type: object
                                    properties:
                                      human_id:
                                        type: string
                                        example: "8"
                                      blacklist_id:
                                        type: string
                                        example: "3"
                                      human_data:
                                        type: object
                                        properties:
                                          face_pic_url:
                                            type: string
                                            example: 0f61ba76b1a6ace23169223c9e30a55ab0308afba90a6a24b48746007437d714e
                                      reserve_field:
                                        type: object
                                        properties:
                                          name:
                                            type: string
                                            example: Dheera Warnakulasuriya
                                      similarity:
                                        type: integer
                                        example: 95
                                  URL:
                                    type: string
                                    example: Vsm://PHQG#20250915#20250915_105814149.d:252760086:450624
                                  faceRect:
                                    type: object
                                    properties:
                                      height:
                                        type: number
                                        example: 0.5740000009536743
                                      width:
                                        type: number
                                        example: 0.19300000369548798
                                      x:
                                        type: number
                                        example: 0.44999998807907107
                                      y:
                                        type: number
                                        example: 0.296999990940094
                                  age:
                                    type: object
                                    properties:
                                      ageGroup:
                                        type: integer
                                        example: 0
                                  gender:
                                    type: object
                                    properties:
                                      value:
                                        type: integer
                                        example: 0
                                  temperature:
                                    type: object
                                    properties:
                                      temperatureData:
                                        type: number
                                        example: 0.0
                                      temperatureStatus:
                                        type: integer
                                        example: -1
                                  mask:
                                    type: object
                                    properties:
                                      wearMaskStatus:
                                        type: integer
                                        example: 0
                          targetAttrs:
                            type: object
                            properties:
                              cameraIndexCode:
                                type: string
                                example: "2"
                              faceTime:
                                type: string
                                format: date-time
                                example: 2025-09-15T13:34:12+05:30
        isHistory:
          type: integer
          example: 0

